<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A FindMyFriends type of Web Application">
    <meta name="author" content="Steven Duckett">
    <link rel="icon" href="Media/Tab-Icon.png" />

    <!--Bootstrap link below this line, along with my own custom CSS styling file -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="CSS/my-style.css" rel="stylesheet">
    <title>FriendBook</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php">FriendBook</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <!-- On this page, the user is not logged in so they can only see a restricted search bar
            just so they can search for user. But they do not have/require the ability to refine the search
            and order results -->
            <form class="d-flex" method="post" action="search.php">
                <input class="form-control me-2" name="userSearchTerm" type="search" placeholder="Search" aria-label="Search" required>
                <select name="searchCriteria" id="searchCriteria">
                    <option>Choose Option</option>
                    <option>First Name</option>
                    <option>Last Name</option>
                    <option>Username</option>
                </select>
                <input type="hidden" name="searchFilter" value="UserID">
                <button class="btn btn-outline-secondary" type="submit" name="searchSubmit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div id="content" class="container-l">